use-grammars = { only = [
  "rust", 
  "toml", 
  "yaml", 
  "hcl", 
  "tfvars", 
  "sql", 
  "sshclientconfig", 
  "bash", 
  "dockerfile", 
  "env", 
  "git-rebase", 
  "git-ignore", 
  "git-config", 
  "git-commit", 
  "git-attributes", 
  "ini", 
  "json", 
  "markdown", 
  "java"
]}

[language-server.rust-analyzer.config]
checkOnSave = true
check = { command = "clippy" }

[language-server.taplo.config]
align-entries = true
reorder_keys = true
reorder_arrays = true
alignEntries = true
reorderKeys = true
reorderArrays = true

[language-server.terraform-ls.config]
indexing.ignoreDirectoryNames = [".helix"]
ignoreSingleFileWarning = true
experimentalFeatures = { prefillRequiredFields = true }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true
completion = true
hover = false

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-inventory.json" = "*azure_rm.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-galaxy.json" = "galaxy.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-ee.json" = "ansible.cfg"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-playbook.json" = "ansible/*.{yml,yaml}"

[[language]]
name = "rust"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{ completion = "filename", name = "binary" }]
args.program = "{0}"
args.runInTerminal = true
