use-grammars = { only = [ "rust", "toml", "yaml", "hcl", "tfvars", "sql", "sshclientconfig", "bash", "dockerfile", "env", "git-rebase", "git-ignore", "git-config", "git-commit", "git-attributes", "ini", "json", "markdown" ] }

[[language]]
name = "rust"
  [language.config]
  checkOnSave = { command = "clippy" }

  [language.debugger]
  command = "codelldb"
  name = "codelldb"
  port-arg = "--port {}"
  transport = "tcp"

  [[language.debugger.templates]]
  name = "binary"
  request = "launch"

  [[language.debugger.templates.completion]]
  completion = "filename"
  name = "binary"

  [language.debugger.templates.args]
  program = "{0}"
  runInTerminal = true

[[language]]
name = "hcl"
config = { rootModules = [
  "deploy/terraform/production",
  "deploy/terraform/preproduction",
  "deploy/terraform/staging",
  "deploy/terraform/xp1"
]}

[[language]]
name = "tfvars"
config = { rootModules = [
  "deploy/terraform/production",
  "deploy/terraform/preproduction",
  "deploy/terraform/staging",
  "deploy/terraform/xp1"
]}
[[language]]
name = "yaml"
  [[language.config.yaml]]
  format = { enable = true }
  validation = true
  completion = true
  hover = true

  [[language.config.yaml.schemas]]
  "https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
  "https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "deploy/ansible/roles/{tasks,handlers}/*.{yml,yaml}"
  "https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-inventory.json" = "deploy/ansible/*azure_rm.{yml,yaml}"
  "https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-galaxy.json" = "deploy/ansible/galaxy.yml"
  "https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-ee.json" = "deploy/ansible/ansible.cfg"
  "https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-playbook.json" = "deploy/ansible/ansible/*[gdp]*.{yml,yaml}"
